<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/13 01:49:20
sfConfig::add(array(
  'mod_administradores_enabled' => true,
  'mod_administradores_view_class' => 'sfPHP',
));
