<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/15 18:12:23
sfConfig::add(array(
  'mod_administradores_enabled' => true,
  'mod_administradores_view_class' => 'sfPHP',
));
