<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/10 22:17:50
sfConfig::add(array(
  'mod_administradores_enabled' => true,
  'mod_administradores_view_class' => 'sfPHP',
));
