<?php


/**
 * This class defines the structure of the 'evaluaciones' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/05/11 21:29:46
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EvaluacionesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EvaluacionesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('evaluaciones');
		$this->setPhpName('Evaluaciones');
		$this->setClassname('Evaluaciones');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addForeignKey('PERFIL_ID', 'PerfilId', 'INTEGER', 'perfil', 'ID', true, 11, null);
		$this->addForeignKey('ESTADOSEVALUACIONES_ID', 'EstadosevaluacionesId', 'INTEGER', 'estadosevaluaciones', 'ID', true, 11, null);
		$this->addColumn('CANTIDAD', 'Cantidad', 'INTEGER', false, 11, null);
		$this->addColumn('NOMBRE', 'Nombre', 'CHAR', false, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Perfil', 'Perfil', RelationMap::MANY_TO_ONE, array('perfil_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Estadosevaluaciones', 'Estadosevaluaciones', RelationMap::MANY_TO_ONE, array('estadosevaluaciones_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Asistencias', 'Asistencias', RelationMap::ONE_TO_MANY, array('id' => 'evaluaciones_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Pruebas', 'Pruebas', RelationMap::ONE_TO_MANY, array('id' => 'evaluaciones_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // EvaluacionesTableMap
