<?php

/**
 * Base class that represents a row from the 'tests' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/25/11 20:25:35
 *
 * @package    lib.model.om
 */
abstract class BaseTests extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TestsPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the titulo field.
	 * @var        string
	 */
	protected $titulo;

	/**
	 * The value for the historia field.
	 * @var        string
	 */
	protected $historia;

	/**
	 * The value for the enunciado field.
	 * @var        string
	 */
	protected $enunciado;

	/**
	 * The value for the imagen field.
	 * @var        string
	 */
	protected $imagen;

	/**
	 * The value for the duracion field.
	 * @var        string
	 */
	protected $duracion;

	/**
	 * The value for the puntaje_aprobacion field.
	 * @var        string
	 */
	protected $puntaje_aprobacion;

	/**
	 * The value for the paginacion field.
	 * @var        int
	 */
	protected $paginacion;

	/**
	 * The value for the tipoopcion_id field.
	 * @var        int
	 */
	protected $tipoopcion_id;

	/**
	 * The value for the tests_id field.
	 * @var        int
	 */
	protected $tests_id;

	/**
	 * @var        Tipoopcion
	 */
	protected $aTipoopcion;

	/**
	 * @var        Tests
	 */
	protected $aTestsRelatedByTestsId;

	/**
	 * @var        array Escalas[] Collection to store aggregation of Escalas objects.
	 */
	protected $collEscalass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEscalass.
	 */
	private $lastEscalasCriteria = null;

	/**
	 * @var        array Preguntas[] Collection to store aggregation of Preguntas objects.
	 */
	protected $collPreguntass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPreguntass.
	 */
	private $lastPreguntasCriteria = null;

	/**
	 * @var        array Pruebas[] Collection to store aggregation of Pruebas objects.
	 */
	protected $collPruebass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPruebass.
	 */
	private $lastPruebasCriteria = null;

	/**
	 * @var        array Tests[] Collection to store aggregation of Tests objects.
	 */
	protected $collTestssRelatedByTestsId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTestssRelatedByTestsId.
	 */
	private $lastTestsRelatedByTestsIdCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TestsPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [titulo] column value.
	 * 
	 * @return     string
	 */
	public function getTitulo()
	{
		return $this->titulo;
	}

	/**
	 * Get the [historia] column value.
	 * 
	 * @return     string
	 */
	public function getHistoria()
	{
		return $this->historia;
	}

	/**
	 * Get the [enunciado] column value.
	 * 
	 * @return     string
	 */
	public function getEnunciado()
	{
		return $this->enunciado;
	}

	/**
	 * Get the [imagen] column value.
	 * 
	 * @return     string
	 */
	public function getImagen()
	{
		return $this->imagen;
	}

	/**
	 * Get the [duracion] column value.
	 * 
	 * @return     string
	 */
	public function getDuracion()
	{
		return $this->duracion;
	}

	/**
	 * Get the [puntaje_aprobacion] column value.
	 * 
	 * @return     string
	 */
	public function getPuntajeAprobacion()
	{
		return $this->puntaje_aprobacion;
	}

	/**
	 * Get the [paginacion] column value.
	 * 
	 * @return     int
	 */
	public function getPaginacion()
	{
		return $this->paginacion;
	}

	/**
	 * Get the [tipoopcion_id] column value.
	 * 
	 * @return     int
	 */
	public function getTipoopcionId()
	{
		return $this->tipoopcion_id;
	}

	/**
	 * Get the [tests_id] column value.
	 * 
	 * @return     int
	 */
	public function getTestsId()
	{
		return $this->tests_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = TestsPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [titulo] column.
	 * 
	 * @param      string $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setTitulo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titulo !== $v) {
			$this->titulo = $v;
			$this->modifiedColumns[] = TestsPeer::TITULO;
		}

		return $this;
	} // setTitulo()

	/**
	 * Set the value of [historia] column.
	 * 
	 * @param      string $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setHistoria($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->historia !== $v) {
			$this->historia = $v;
			$this->modifiedColumns[] = TestsPeer::HISTORIA;
		}

		return $this;
	} // setHistoria()

	/**
	 * Set the value of [enunciado] column.
	 * 
	 * @param      string $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setEnunciado($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->enunciado !== $v) {
			$this->enunciado = $v;
			$this->modifiedColumns[] = TestsPeer::ENUNCIADO;
		}

		return $this;
	} // setEnunciado()

	/**
	 * Set the value of [imagen] column.
	 * 
	 * @param      string $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setImagen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->imagen !== $v) {
			$this->imagen = $v;
			$this->modifiedColumns[] = TestsPeer::IMAGEN;
		}

		return $this;
	} // setImagen()

	/**
	 * Set the value of [duracion] column.
	 * 
	 * @param      string $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setDuracion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->duracion !== $v) {
			$this->duracion = $v;
			$this->modifiedColumns[] = TestsPeer::DURACION;
		}

		return $this;
	} // setDuracion()

	/**
	 * Set the value of [puntaje_aprobacion] column.
	 * 
	 * @param      string $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setPuntajeAprobacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->puntaje_aprobacion !== $v) {
			$this->puntaje_aprobacion = $v;
			$this->modifiedColumns[] = TestsPeer::PUNTAJE_APROBACION;
		}

		return $this;
	} // setPuntajeAprobacion()

	/**
	 * Set the value of [paginacion] column.
	 * 
	 * @param      int $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setPaginacion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->paginacion !== $v) {
			$this->paginacion = $v;
			$this->modifiedColumns[] = TestsPeer::PAGINACION;
		}

		return $this;
	} // setPaginacion()

	/**
	 * Set the value of [tipoopcion_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setTipoopcionId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tipoopcion_id !== $v) {
			$this->tipoopcion_id = $v;
			$this->modifiedColumns[] = TestsPeer::TIPOOPCION_ID;
		}

		if ($this->aTipoopcion !== null && $this->aTipoopcion->getId() !== $v) {
			$this->aTipoopcion = null;
		}

		return $this;
	} // setTipoopcionId()

	/**
	 * Set the value of [tests_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Tests The current object (for fluent API support)
	 */
	public function setTestsId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tests_id !== $v) {
			$this->tests_id = $v;
			$this->modifiedColumns[] = TestsPeer::TESTS_ID;
		}

		if ($this->aTestsRelatedByTestsId !== null && $this->aTestsRelatedByTestsId->getId() !== $v) {
			$this->aTestsRelatedByTestsId = null;
		}

		return $this;
	} // setTestsId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->titulo = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->historia = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->enunciado = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->imagen = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->duracion = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->puntaje_aprobacion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->paginacion = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->tipoopcion_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->tests_id = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = TestsPeer::NUM_COLUMNS - TestsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tests object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTipoopcion !== null && $this->tipoopcion_id !== $this->aTipoopcion->getId()) {
			$this->aTipoopcion = null;
		}
		if ($this->aTestsRelatedByTestsId !== null && $this->tests_id !== $this->aTestsRelatedByTestsId->getId()) {
			$this->aTestsRelatedByTestsId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TestsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TestsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTipoopcion = null;
			$this->aTestsRelatedByTestsId = null;
			$this->collEscalass = null;
			$this->lastEscalasCriteria = null;

			$this->collPreguntass = null;
			$this->lastPreguntasCriteria = null;

			$this->collPruebass = null;
			$this->lastPruebasCriteria = null;

			$this->collTestssRelatedByTestsId = null;
			$this->lastTestsRelatedByTestsIdCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TestsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTests:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				TestsPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTests:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TestsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTests:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTests:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				TestsPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTipoopcion !== null) {
				if ($this->aTipoopcion->isModified() || $this->aTipoopcion->isNew()) {
					$affectedRows += $this->aTipoopcion->save($con);
				}
				$this->setTipoopcion($this->aTipoopcion);
			}

			if ($this->aTestsRelatedByTestsId !== null) {
				if ($this->aTestsRelatedByTestsId->isModified() || $this->aTestsRelatedByTestsId->isNew()) {
					$affectedRows += $this->aTestsRelatedByTestsId->save($con);
				}
				$this->setTestsRelatedByTestsId($this->aTestsRelatedByTestsId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TestsPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TestsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TestsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collEscalass !== null) {
				foreach ($this->collEscalass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPreguntass !== null) {
				foreach ($this->collPreguntass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPruebass !== null) {
				foreach ($this->collPruebass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTestssRelatedByTestsId !== null) {
				foreach ($this->collTestssRelatedByTestsId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTipoopcion !== null) {
				if (!$this->aTipoopcion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipoopcion->getValidationFailures());
				}
			}

			if ($this->aTestsRelatedByTestsId !== null) {
				if (!$this->aTestsRelatedByTestsId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTestsRelatedByTestsId->getValidationFailures());
				}
			}


			if (($retval = TestsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collEscalass !== null) {
					foreach ($this->collEscalass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPreguntass !== null) {
					foreach ($this->collPreguntass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPruebass !== null) {
					foreach ($this->collPruebass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTestssRelatedByTestsId !== null) {
					foreach ($this->collTestssRelatedByTestsId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TestsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTitulo();
				break;
			case 2:
				return $this->getHistoria();
				break;
			case 3:
				return $this->getEnunciado();
				break;
			case 4:
				return $this->getImagen();
				break;
			case 5:
				return $this->getDuracion();
				break;
			case 6:
				return $this->getPuntajeAprobacion();
				break;
			case 7:
				return $this->getPaginacion();
				break;
			case 8:
				return $this->getTipoopcionId();
				break;
			case 9:
				return $this->getTestsId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TestsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTitulo(),
			$keys[2] => $this->getHistoria(),
			$keys[3] => $this->getEnunciado(),
			$keys[4] => $this->getImagen(),
			$keys[5] => $this->getDuracion(),
			$keys[6] => $this->getPuntajeAprobacion(),
			$keys[7] => $this->getPaginacion(),
			$keys[8] => $this->getTipoopcionId(),
			$keys[9] => $this->getTestsId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TestsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTitulo($value);
				break;
			case 2:
				$this->setHistoria($value);
				break;
			case 3:
				$this->setEnunciado($value);
				break;
			case 4:
				$this->setImagen($value);
				break;
			case 5:
				$this->setDuracion($value);
				break;
			case 6:
				$this->setPuntajeAprobacion($value);
				break;
			case 7:
				$this->setPaginacion($value);
				break;
			case 8:
				$this->setTipoopcionId($value);
				break;
			case 9:
				$this->setTestsId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TestsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTitulo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setHistoria($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setEnunciado($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setImagen($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDuracion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPuntajeAprobacion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPaginacion($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTipoopcionId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setTestsId($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TestsPeer::DATABASE_NAME);

		if ($this->isColumnModified(TestsPeer::ID)) $criteria->add(TestsPeer::ID, $this->id);
		if ($this->isColumnModified(TestsPeer::TITULO)) $criteria->add(TestsPeer::TITULO, $this->titulo);
		if ($this->isColumnModified(TestsPeer::HISTORIA)) $criteria->add(TestsPeer::HISTORIA, $this->historia);
		if ($this->isColumnModified(TestsPeer::ENUNCIADO)) $criteria->add(TestsPeer::ENUNCIADO, $this->enunciado);
		if ($this->isColumnModified(TestsPeer::IMAGEN)) $criteria->add(TestsPeer::IMAGEN, $this->imagen);
		if ($this->isColumnModified(TestsPeer::DURACION)) $criteria->add(TestsPeer::DURACION, $this->duracion);
		if ($this->isColumnModified(TestsPeer::PUNTAJE_APROBACION)) $criteria->add(TestsPeer::PUNTAJE_APROBACION, $this->puntaje_aprobacion);
		if ($this->isColumnModified(TestsPeer::PAGINACION)) $criteria->add(TestsPeer::PAGINACION, $this->paginacion);
		if ($this->isColumnModified(TestsPeer::TIPOOPCION_ID)) $criteria->add(TestsPeer::TIPOOPCION_ID, $this->tipoopcion_id);
		if ($this->isColumnModified(TestsPeer::TESTS_ID)) $criteria->add(TestsPeer::TESTS_ID, $this->tests_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TestsPeer::DATABASE_NAME);

		$criteria->add(TestsPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tests (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTitulo($this->titulo);

		$copyObj->setHistoria($this->historia);

		$copyObj->setEnunciado($this->enunciado);

		$copyObj->setImagen($this->imagen);

		$copyObj->setDuracion($this->duracion);

		$copyObj->setPuntajeAprobacion($this->puntaje_aprobacion);

		$copyObj->setPaginacion($this->paginacion);

		$copyObj->setTipoopcionId($this->tipoopcion_id);

		$copyObj->setTestsId($this->tests_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getEscalass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEscalas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPreguntass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPreguntas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPruebass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPruebas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTestssRelatedByTestsId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTestsRelatedByTestsId($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tests Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TestsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TestsPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Tipoopcion object.
	 *
	 * @param      Tipoopcion $v
	 * @return     Tests The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipoopcion(Tipoopcion $v = null)
	{
		if ($v === null) {
			$this->setTipoopcionId(NULL);
		} else {
			$this->setTipoopcionId($v->getId());
		}

		$this->aTipoopcion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tipoopcion object, it will not be re-added.
		if ($v !== null) {
			$v->addTests($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tipoopcion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tipoopcion The associated Tipoopcion object.
	 * @throws     PropelException
	 */
	public function getTipoopcion(PropelPDO $con = null)
	{
		if ($this->aTipoopcion === null && ($this->tipoopcion_id !== null)) {
			$this->aTipoopcion = TipoopcionPeer::retrieveByPk($this->tipoopcion_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTipoopcion->addTestss($this);
			 */
		}
		return $this->aTipoopcion;
	}

	/**
	 * Declares an association between this object and a Tests object.
	 *
	 * @param      Tests $v
	 * @return     Tests The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTestsRelatedByTestsId(Tests $v = null)
	{
		if ($v === null) {
			$this->setTestsId(NULL);
		} else {
			$this->setTestsId($v->getId());
		}

		$this->aTestsRelatedByTestsId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tests object, it will not be re-added.
		if ($v !== null) {
			$v->addTestsRelatedByTestsId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tests object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tests The associated Tests object.
	 * @throws     PropelException
	 */
	public function getTestsRelatedByTestsId(PropelPDO $con = null)
	{
		if ($this->aTestsRelatedByTestsId === null && ($this->tests_id !== null)) {
			$this->aTestsRelatedByTestsId = TestsPeer::retrieveByPk($this->tests_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTestsRelatedByTestsId->addTestssRelatedByTestsId($this);
			 */
		}
		return $this->aTestsRelatedByTestsId;
	}

	/**
	 * Clears out the collEscalass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEscalass()
	 */
	public function clearEscalass()
	{
		$this->collEscalass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEscalass collection (array).
	 *
	 * By default this just sets the collEscalass collection to an empty array (like clearcollEscalass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEscalass()
	{
		$this->collEscalass = array();
	}

	/**
	 * Gets an array of Escalas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tests has previously been saved, it will retrieve
	 * related Escalass from storage. If this Tests is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Escalas[]
	 * @throws     PropelException
	 */
	public function getEscalass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEscalass === null) {
			if ($this->isNew()) {
			   $this->collEscalass = array();
			} else {

				$criteria->add(EscalasPeer::TESTS_ID, $this->id);

				EscalasPeer::addSelectColumns($criteria);
				$this->collEscalass = EscalasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EscalasPeer::TESTS_ID, $this->id);

				EscalasPeer::addSelectColumns($criteria);
				if (!isset($this->lastEscalasCriteria) || !$this->lastEscalasCriteria->equals($criteria)) {
					$this->collEscalass = EscalasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEscalasCriteria = $criteria;
		return $this->collEscalass;
	}

	/**
	 * Returns the number of related Escalas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Escalas objects.
	 * @throws     PropelException
	 */
	public function countEscalass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEscalass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EscalasPeer::TESTS_ID, $this->id);

				$count = EscalasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EscalasPeer::TESTS_ID, $this->id);

				if (!isset($this->lastEscalasCriteria) || !$this->lastEscalasCriteria->equals($criteria)) {
					$count = EscalasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collEscalass);
				}
			} else {
				$count = count($this->collEscalass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Escalas object to this object
	 * through the Escalas foreign key attribute.
	 *
	 * @param      Escalas $l Escalas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEscalas(Escalas $l)
	{
		if ($this->collEscalass === null) {
			$this->initEscalass();
		}
		if (!in_array($l, $this->collEscalass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEscalass, $l);
			$l->setTests($this);
		}
	}

	/**
	 * Clears out the collPreguntass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPreguntass()
	 */
	public function clearPreguntass()
	{
		$this->collPreguntass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPreguntass collection (array).
	 *
	 * By default this just sets the collPreguntass collection to an empty array (like clearcollPreguntass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPreguntass()
	{
		$this->collPreguntass = array();
	}

	/**
	 * Gets an array of Preguntas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tests has previously been saved, it will retrieve
	 * related Preguntass from storage. If this Tests is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Preguntas[]
	 * @throws     PropelException
	 */
	public function getPreguntass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPreguntass === null) {
			if ($this->isNew()) {
			   $this->collPreguntass = array();
			} else {

				$criteria->add(PreguntasPeer::TESTS_ID, $this->id);

				PreguntasPeer::addSelectColumns($criteria);
				$this->collPreguntass = PreguntasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PreguntasPeer::TESTS_ID, $this->id);

				PreguntasPeer::addSelectColumns($criteria);
				if (!isset($this->lastPreguntasCriteria) || !$this->lastPreguntasCriteria->equals($criteria)) {
					$this->collPreguntass = PreguntasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPreguntasCriteria = $criteria;
		return $this->collPreguntass;
	}

	/**
	 * Returns the number of related Preguntas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Preguntas objects.
	 * @throws     PropelException
	 */
	public function countPreguntass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPreguntass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PreguntasPeer::TESTS_ID, $this->id);

				$count = PreguntasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PreguntasPeer::TESTS_ID, $this->id);

				if (!isset($this->lastPreguntasCriteria) || !$this->lastPreguntasCriteria->equals($criteria)) {
					$count = PreguntasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPreguntass);
				}
			} else {
				$count = count($this->collPreguntass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Preguntas object to this object
	 * through the Preguntas foreign key attribute.
	 *
	 * @param      Preguntas $l Preguntas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPreguntas(Preguntas $l)
	{
		if ($this->collPreguntass === null) {
			$this->initPreguntass();
		}
		if (!in_array($l, $this->collPreguntass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPreguntass, $l);
			$l->setTests($this);
		}
	}

	/**
	 * Clears out the collPruebass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPruebass()
	 */
	public function clearPruebass()
	{
		$this->collPruebass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPruebass collection (array).
	 *
	 * By default this just sets the collPruebass collection to an empty array (like clearcollPruebass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPruebass()
	{
		$this->collPruebass = array();
	}

	/**
	 * Gets an array of Pruebas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tests has previously been saved, it will retrieve
	 * related Pruebass from storage. If this Tests is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Pruebas[]
	 * @throws     PropelException
	 */
	public function getPruebass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPruebass === null) {
			if ($this->isNew()) {
			   $this->collPruebass = array();
			} else {

				$criteria->add(PruebasPeer::TESTS_ID, $this->id);

				PruebasPeer::addSelectColumns($criteria);
				$this->collPruebass = PruebasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PruebasPeer::TESTS_ID, $this->id);

				PruebasPeer::addSelectColumns($criteria);
				if (!isset($this->lastPruebasCriteria) || !$this->lastPruebasCriteria->equals($criteria)) {
					$this->collPruebass = PruebasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPruebasCriteria = $criteria;
		return $this->collPruebass;
	}

	/**
	 * Returns the number of related Pruebas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Pruebas objects.
	 * @throws     PropelException
	 */
	public function countPruebass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPruebass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PruebasPeer::TESTS_ID, $this->id);

				$count = PruebasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PruebasPeer::TESTS_ID, $this->id);

				if (!isset($this->lastPruebasCriteria) || !$this->lastPruebasCriteria->equals($criteria)) {
					$count = PruebasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPruebass);
				}
			} else {
				$count = count($this->collPruebass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Pruebas object to this object
	 * through the Pruebas foreign key attribute.
	 *
	 * @param      Pruebas $l Pruebas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPruebas(Pruebas $l)
	{
		if ($this->collPruebass === null) {
			$this->initPruebass();
		}
		if (!in_array($l, $this->collPruebass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPruebass, $l);
			$l->setTests($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tests is new, it will return
	 * an empty collection; or if this Tests has previously
	 * been saved, it will retrieve related Pruebass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tests.
	 */
	public function getPruebassJoinEvaluaciones($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPruebass === null) {
			if ($this->isNew()) {
				$this->collPruebass = array();
			} else {

				$criteria->add(PruebasPeer::TESTS_ID, $this->id);

				$this->collPruebass = PruebasPeer::doSelectJoinEvaluaciones($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PruebasPeer::TESTS_ID, $this->id);

			if (!isset($this->lastPruebasCriteria) || !$this->lastPruebasCriteria->equals($criteria)) {
				$this->collPruebass = PruebasPeer::doSelectJoinEvaluaciones($criteria, $con, $join_behavior);
			}
		}
		$this->lastPruebasCriteria = $criteria;

		return $this->collPruebass;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tests is new, it will return
	 * an empty collection; or if this Tests has previously
	 * been saved, it will retrieve related Pruebass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tests.
	 */
	public function getPruebassJoinEstadopruebas($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPruebass === null) {
			if ($this->isNew()) {
				$this->collPruebass = array();
			} else {

				$criteria->add(PruebasPeer::TESTS_ID, $this->id);

				$this->collPruebass = PruebasPeer::doSelectJoinEstadopruebas($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PruebasPeer::TESTS_ID, $this->id);

			if (!isset($this->lastPruebasCriteria) || !$this->lastPruebasCriteria->equals($criteria)) {
				$this->collPruebass = PruebasPeer::doSelectJoinEstadopruebas($criteria, $con, $join_behavior);
			}
		}
		$this->lastPruebasCriteria = $criteria;

		return $this->collPruebass;
	}

	/**
	 * Clears out the collTestssRelatedByTestsId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTestssRelatedByTestsId()
	 */
	public function clearTestssRelatedByTestsId()
	{
		$this->collTestssRelatedByTestsId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTestssRelatedByTestsId collection (array).
	 *
	 * By default this just sets the collTestssRelatedByTestsId collection to an empty array (like clearcollTestssRelatedByTestsId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTestssRelatedByTestsId()
	{
		$this->collTestssRelatedByTestsId = array();
	}

	/**
	 * Gets an array of Tests objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tests has previously been saved, it will retrieve
	 * related TestssRelatedByTestsId from storage. If this Tests is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tests[]
	 * @throws     PropelException
	 */
	public function getTestssRelatedByTestsId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTestssRelatedByTestsId === null) {
			if ($this->isNew()) {
			   $this->collTestssRelatedByTestsId = array();
			} else {

				$criteria->add(TestsPeer::TESTS_ID, $this->id);

				TestsPeer::addSelectColumns($criteria);
				$this->collTestssRelatedByTestsId = TestsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TestsPeer::TESTS_ID, $this->id);

				TestsPeer::addSelectColumns($criteria);
				if (!isset($this->lastTestsRelatedByTestsIdCriteria) || !$this->lastTestsRelatedByTestsIdCriteria->equals($criteria)) {
					$this->collTestssRelatedByTestsId = TestsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTestsRelatedByTestsIdCriteria = $criteria;
		return $this->collTestssRelatedByTestsId;
	}

	/**
	 * Returns the number of related Tests objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tests objects.
	 * @throws     PropelException
	 */
	public function countTestssRelatedByTestsId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTestssRelatedByTestsId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TestsPeer::TESTS_ID, $this->id);

				$count = TestsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TestsPeer::TESTS_ID, $this->id);

				if (!isset($this->lastTestsRelatedByTestsIdCriteria) || !$this->lastTestsRelatedByTestsIdCriteria->equals($criteria)) {
					$count = TestsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTestssRelatedByTestsId);
				}
			} else {
				$count = count($this->collTestssRelatedByTestsId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tests object to this object
	 * through the Tests foreign key attribute.
	 *
	 * @param      Tests $l Tests
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTestsRelatedByTestsId(Tests $l)
	{
		if ($this->collTestssRelatedByTestsId === null) {
			$this->initTestssRelatedByTestsId();
		}
		if (!in_array($l, $this->collTestssRelatedByTestsId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTestssRelatedByTestsId, $l);
			$l->setTestsRelatedByTestsId($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tests is new, it will return
	 * an empty collection; or if this Tests has previously
	 * been saved, it will retrieve related TestssRelatedByTestsId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tests.
	 */
	public function getTestssRelatedByTestsIdJoinTipoopcion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TestsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTestssRelatedByTestsId === null) {
			if ($this->isNew()) {
				$this->collTestssRelatedByTestsId = array();
			} else {

				$criteria->add(TestsPeer::TESTS_ID, $this->id);

				$this->collTestssRelatedByTestsId = TestsPeer::doSelectJoinTipoopcion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TestsPeer::TESTS_ID, $this->id);

			if (!isset($this->lastTestsRelatedByTestsIdCriteria) || !$this->lastTestsRelatedByTestsIdCriteria->equals($criteria)) {
				$this->collTestssRelatedByTestsId = TestsPeer::doSelectJoinTipoopcion($criteria, $con, $join_behavior);
			}
		}
		$this->lastTestsRelatedByTestsIdCriteria = $criteria;

		return $this->collTestssRelatedByTestsId;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collEscalass) {
				foreach ((array) $this->collEscalass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPreguntass) {
				foreach ((array) $this->collPreguntass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPruebass) {
				foreach ((array) $this->collPruebass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTestssRelatedByTestsId) {
				foreach ((array) $this->collTestssRelatedByTestsId as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collEscalass = null;
		$this->collPreguntass = null;
		$this->collPruebass = null;
		$this->collTestssRelatedByTestsId = null;
			$this->aTipoopcion = null;
			$this->aTestsRelatedByTestsId = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTests:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTests::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTests
