<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/14 19:44:00
sfConfig::add(array(
  'mod_administradores_enabled' => true,
  'mod_administradores_view_class' => 'sfPHP',
));
