<?php


/**
 * Skeleton subclass for representing a row from the 'aspirantes' table.
 *
 * 
 *
 * This class was autogenerated by Propel sfContext::getInstance()-getUser()-getAttribute('usuarioId').4.2 on:
 *
 * 09/28/sfContext::getInstance()-getUser()-getAttribute('usuarioId')sfContext::getInstance()-getUser()-getAttribute('usuarioId') sfContext::getInstance()-getUser()-getAttribute('usuarioId')7:sfContext::getInstance()-getUser()-getAttribute('usuarioId')0:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Aspirantes extends BaseAspirantes 
{
 public function postInsert(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
             $auditoria->setObjeto('Aspirantes');
             $auditoria->setDescripcion(' Cedula : '.$this->getCedula().' Nombre : '.$this->getNombre().' Apellido : '.$this->getApellido());
             $auditoria->setTipooperacion('Alta de aspirante');
             $auditoria->save();             
     }
     
      public function postUpdate(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
             $auditoria->setObjeto('Aspirantes');
             $auditoria->setDescripcion(' Cedula : '.$this->getCedula().' Nombre : '.$this->getNombre().' Apellido : '.$this->getApellido());
             $auditoria->setTipooperacion('Modificación de aspirante');
             $auditoria->save();   
     }
     
     
     public function postDelete(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
             $auditoria->setObjeto('Aspirantes');
             $auditoria->setDescripcion(' Cedula : '.$this->getCedula().' Nombre : '.$this->getNombre().' Apellido : '.$this->getApellido());
             $auditoria->setTipooperacion('Eliminación de aspirante');
             $auditoria->save();        
     }
} // Aspirantes
