<?php


/**
 * Skeleton subclass for performing query and update operations on the 'evaluaciones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/11 17:10:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EvaluacionesPeer extends BaseEvaluacionesPeer 
{
 public static function getEvaluaciones($estado,$pagina,$rows,$nombre,$fecha)
  {
    $criteria = new Criteria();    
    if($nombre!="")
        $criteria->add(EvaluacionesPeer::NOMBRE,$nombre,Criteria::EQUAL);     
    if($fecha!="--")
        $criteria->add(EvaluacionesPeer::FECHA,$fecha,Criteria::EQUAL);     
    
    $criteria->add(EvaluacionesPeer::ESTADOSEVALUACIONES_ID,$estado,Criteria::EQUAL);     
    $pager = new PropelPager($criteria, 'EvaluacionesPeer', 'doSelectJoinAll', $page = $pagina, $rows);
    return $pager;
  }
  
  public static function getEvaluacionesAspirantes($estado,$aspirante)
  {
    $criteria = new Criteria();    
    $criteria->add(AsistenciasPeer::ASPIRANTES_ID,$aspirante,Criteria::EQUAL);     
    $criteria->add(EvaluacionesPeer::ESTADOSEVALUACIONES_ID,$estado,Criteria::EQUAL);         
    return (AsistenciasPeer::doSelectJoinAll($criteria));
  }
  
  public static function getAll()
  {
    $criteria = new Criteria();      
    return (self::doSelectJoinAll($criteria));
  }
  
} // EvaluacionesPeer
