<?php


/**
 * Skeleton subclass for performing query and update operations on the 'intensidades' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/12/11 19:48:31
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class IntensidadesPeer extends BaseIntensidadesPeer {

} // IntensidadesPeer
