<?php


/**
 * Skeleton subclass for performing query and update operations on the 'pruebas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/11 17:10:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PruebasPeer extends BasePruebasPeer 
{
  public static function getPruebas($evaluacion)
  {
    $criteria = new Criteria();
    $criteria->add(PruebasPeer::EVALUACIONES_ID,$evaluacion,Criteria::EQUAL); 
    return (self::doSelectJoinAll($criteria));
  }
  
  
  public static function getPruebasPaged($evaluacion,$pagina,$rows)
  {
    $criteria = new Criteria();
    $criteria->add(PruebasPeer::EVALUACIONES_ID,$evaluacion,Criteria::EQUAL); 
    $pager = new PropelPager($criteria, 'PruebasPeer', 'doSelectJoinAll', $page = $pagina, $rows);
    return $pager;
  }
  
} // PruebasPeer
