<?php


/**
 * Skeleton subclass for performing query and update operations on the 'respuestas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/11 17:10:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RespuestasPeer extends BaseRespuestasPeer 
{
    
public static function getResponse($respuesta)
  {
    $criteria = new Criteria();    

    $criteria->add(RespuestasPeer::TEXTO,$respuesta,Criteria::EQUAL);     
    return (self::doSelectOne($criteria));
  }
  
  
  public static function getRespuesta($pregunta)
  {
    $criteria = new Criteria();    

    $criteria->add(RespuestasPeer::PREGUNTAS_ID,$pregunta,Criteria::EQUAL);     
    return (self::doSelectOne($criteria));
  }
} // RespuestasPeer
