<?php


/**
 * Skeleton subclass for performing query and update operations on the 'resultadosparciales' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/11 22:16:56
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ResultadosparcialesPeer extends BaseResultadosparcialesPeer 
{
 public static function getResultadosParciales($prueba,$aspirante)
  {
    $criteria = new Criteria();    

    $criteria->add(ResultadosparcialesPeer::PRUEBAS_ID,$prueba,Criteria::EQUAL);     
    $criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID,$aspirante,Criteria::EQUAL);    
    return (self::doSelectJoinAll($criteria));
  }
  
  
} // ResultadosparcialesPeer
