<?php

/**
 * Base class that represents a row from the 'escalas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/11/11 16:15:19
 *
 * @package    lib.model.om
 */
abstract class BaseEscalas extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EscalasPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the tests_id field.
	 * @var        int
	 */
	protected $tests_id;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the nombrelargo field.
	 * @var        string
	 */
	protected $nombrelargo;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * @var        Tests
	 */
	protected $aTests;

	/**
	 * @var        array Percentiles[] Collection to store aggregation of Percentiles objects.
	 */
	protected $collPercentiless;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPercentiless.
	 */
	private $lastPercentilesCriteria = null;

	/**
	 * @var        array Respuestasescalas[] Collection to store aggregation of Respuestasescalas objects.
	 */
	protected $collRespuestasescalass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRespuestasescalass.
	 */
	private $lastRespuestasescalasCriteria = null;

	/**
	 * @var        array Resultadosescalas[] Collection to store aggregation of Resultadosescalas objects.
	 */
	protected $collResultadosescalass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collResultadosescalass.
	 */
	private $lastResultadosescalasCriteria = null;

	/**
	 * @var        array Valoresperado[] Collection to store aggregation of Valoresperado objects.
	 */
	protected $collValoresperados;

	/**
	 * @var        Criteria The criteria used to select the current contents of collValoresperados.
	 */
	private $lastValoresperadoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'EscalasPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [tests_id] column value.
	 * 
	 * @return     int
	 */
	public function getTestsId()
	{
		return $this->tests_id;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [nombrelargo] column value.
	 * 
	 * @return     string
	 */
	public function getNombrelargo()
	{
		return $this->nombrelargo;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Escalas The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EscalasPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [tests_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Escalas The current object (for fluent API support)
	 */
	public function setTestsId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tests_id !== $v) {
			$this->tests_id = $v;
			$this->modifiedColumns[] = EscalasPeer::TESTS_ID;
		}

		if ($this->aTests !== null && $this->aTests->getId() !== $v) {
			$this->aTests = null;
		}

		return $this;
	} // setTestsId()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Escalas The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = EscalasPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [nombrelargo] column.
	 * 
	 * @param      string $v new value
	 * @return     Escalas The current object (for fluent API support)
	 */
	public function setNombrelargo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombrelargo !== $v) {
			$this->nombrelargo = $v;
			$this->modifiedColumns[] = EscalasPeer::NOMBRELARGO;
		}

		return $this;
	} // setNombrelargo()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     Escalas The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = EscalasPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->tests_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->nombre = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->nombrelargo = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->descripcion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = EscalasPeer::NUM_COLUMNS - EscalasPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Escalas object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTests !== null && $this->tests_id !== $this->aTests->getId()) {
			$this->aTests = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EscalasPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EscalasPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTests = null;
			$this->collPercentiless = null;
			$this->lastPercentilesCriteria = null;

			$this->collRespuestasescalass = null;
			$this->lastRespuestasescalasCriteria = null;

			$this->collResultadosescalass = null;
			$this->lastResultadosescalasCriteria = null;

			$this->collValoresperados = null;
			$this->lastValoresperadoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EscalasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEscalas:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				EscalasPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEscalas:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EscalasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseEscalas:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseEscalas:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				EscalasPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTests !== null) {
				if ($this->aTests->isModified() || $this->aTests->isNew()) {
					$affectedRows += $this->aTests->save($con);
				}
				$this->setTests($this->aTests);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EscalasPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EscalasPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EscalasPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPercentiless !== null) {
				foreach ($this->collPercentiless as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRespuestasescalass !== null) {
				foreach ($this->collRespuestasescalass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collResultadosescalass !== null) {
				foreach ($this->collResultadosescalass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collValoresperados !== null) {
				foreach ($this->collValoresperados as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTests !== null) {
				if (!$this->aTests->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTests->getValidationFailures());
				}
			}


			if (($retval = EscalasPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPercentiless !== null) {
					foreach ($this->collPercentiless as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRespuestasescalass !== null) {
					foreach ($this->collRespuestasescalass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collResultadosescalass !== null) {
					foreach ($this->collResultadosescalass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collValoresperados !== null) {
					foreach ($this->collValoresperados as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EscalasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTestsId();
				break;
			case 2:
				return $this->getNombre();
				break;
			case 3:
				return $this->getNombrelargo();
				break;
			case 4:
				return $this->getDescripcion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EscalasPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTestsId(),
			$keys[2] => $this->getNombre(),
			$keys[3] => $this->getNombrelargo(),
			$keys[4] => $this->getDescripcion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EscalasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTestsId($value);
				break;
			case 2:
				$this->setNombre($value);
				break;
			case 3:
				$this->setNombrelargo($value);
				break;
			case 4:
				$this->setDescripcion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EscalasPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTestsId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNombre($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNombrelargo($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDescripcion($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EscalasPeer::DATABASE_NAME);

		if ($this->isColumnModified(EscalasPeer::ID)) $criteria->add(EscalasPeer::ID, $this->id);
		if ($this->isColumnModified(EscalasPeer::TESTS_ID)) $criteria->add(EscalasPeer::TESTS_ID, $this->tests_id);
		if ($this->isColumnModified(EscalasPeer::NOMBRE)) $criteria->add(EscalasPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(EscalasPeer::NOMBRELARGO)) $criteria->add(EscalasPeer::NOMBRELARGO, $this->nombrelargo);
		if ($this->isColumnModified(EscalasPeer::DESCRIPCION)) $criteria->add(EscalasPeer::DESCRIPCION, $this->descripcion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EscalasPeer::DATABASE_NAME);

		$criteria->add(EscalasPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Escalas (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTestsId($this->tests_id);

		$copyObj->setNombre($this->nombre);

		$copyObj->setNombrelargo($this->nombrelargo);

		$copyObj->setDescripcion($this->descripcion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPercentiless() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPercentiles($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRespuestasescalass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRespuestasescalas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getResultadosescalass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addResultadosescalas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getValoresperados() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addValoresperado($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Escalas Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EscalasPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EscalasPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Tests object.
	 *
	 * @param      Tests $v
	 * @return     Escalas The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTests(Tests $v = null)
	{
		if ($v === null) {
			$this->setTestsId(NULL);
		} else {
			$this->setTestsId($v->getId());
		}

		$this->aTests = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tests object, it will not be re-added.
		if ($v !== null) {
			$v->addEscalas($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tests object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tests The associated Tests object.
	 * @throws     PropelException
	 */
	public function getTests(PropelPDO $con = null)
	{
		if ($this->aTests === null && ($this->tests_id !== null)) {
			$this->aTests = TestsPeer::retrieveByPk($this->tests_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTests->addEscalass($this);
			 */
		}
		return $this->aTests;
	}

	/**
	 * Clears out the collPercentiless collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPercentiless()
	 */
	public function clearPercentiless()
	{
		$this->collPercentiless = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPercentiless collection (array).
	 *
	 * By default this just sets the collPercentiless collection to an empty array (like clearcollPercentiless());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPercentiless()
	{
		$this->collPercentiless = array();
	}

	/**
	 * Gets an array of Percentiles objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Escalas has previously been saved, it will retrieve
	 * related Percentiless from storage. If this Escalas is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Percentiles[]
	 * @throws     PropelException
	 */
	public function getPercentiless($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPercentiless === null) {
			if ($this->isNew()) {
			   $this->collPercentiless = array();
			} else {

				$criteria->add(PercentilesPeer::ESCALAS_ID, $this->id);

				PercentilesPeer::addSelectColumns($criteria);
				$this->collPercentiless = PercentilesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PercentilesPeer::ESCALAS_ID, $this->id);

				PercentilesPeer::addSelectColumns($criteria);
				if (!isset($this->lastPercentilesCriteria) || !$this->lastPercentilesCriteria->equals($criteria)) {
					$this->collPercentiless = PercentilesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPercentilesCriteria = $criteria;
		return $this->collPercentiless;
	}

	/**
	 * Returns the number of related Percentiles objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Percentiles objects.
	 * @throws     PropelException
	 */
	public function countPercentiless(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPercentiless === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PercentilesPeer::ESCALAS_ID, $this->id);

				$count = PercentilesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PercentilesPeer::ESCALAS_ID, $this->id);

				if (!isset($this->lastPercentilesCriteria) || !$this->lastPercentilesCriteria->equals($criteria)) {
					$count = PercentilesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPercentiless);
				}
			} else {
				$count = count($this->collPercentiless);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Percentiles object to this object
	 * through the Percentiles foreign key attribute.
	 *
	 * @param      Percentiles $l Percentiles
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPercentiles(Percentiles $l)
	{
		if ($this->collPercentiless === null) {
			$this->initPercentiless();
		}
		if (!in_array($l, $this->collPercentiless, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPercentiless, $l);
			$l->setEscalas($this);
		}
	}

	/**
	 * Clears out the collRespuestasescalass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRespuestasescalass()
	 */
	public function clearRespuestasescalass()
	{
		$this->collRespuestasescalass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRespuestasescalass collection (array).
	 *
	 * By default this just sets the collRespuestasescalass collection to an empty array (like clearcollRespuestasescalass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRespuestasescalass()
	{
		$this->collRespuestasescalass = array();
	}

	/**
	 * Gets an array of Respuestasescalas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Escalas has previously been saved, it will retrieve
	 * related Respuestasescalass from storage. If this Escalas is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Respuestasescalas[]
	 * @throws     PropelException
	 */
	public function getRespuestasescalass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRespuestasescalass === null) {
			if ($this->isNew()) {
			   $this->collRespuestasescalass = array();
			} else {

				$criteria->add(RespuestasescalasPeer::ESCALAS_ID, $this->id);

				RespuestasescalasPeer::addSelectColumns($criteria);
				$this->collRespuestasescalass = RespuestasescalasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RespuestasescalasPeer::ESCALAS_ID, $this->id);

				RespuestasescalasPeer::addSelectColumns($criteria);
				if (!isset($this->lastRespuestasescalasCriteria) || !$this->lastRespuestasescalasCriteria->equals($criteria)) {
					$this->collRespuestasescalass = RespuestasescalasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRespuestasescalasCriteria = $criteria;
		return $this->collRespuestasescalass;
	}

	/**
	 * Returns the number of related Respuestasescalas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Respuestasescalas objects.
	 * @throws     PropelException
	 */
	public function countRespuestasescalass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRespuestasescalass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RespuestasescalasPeer::ESCALAS_ID, $this->id);

				$count = RespuestasescalasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RespuestasescalasPeer::ESCALAS_ID, $this->id);

				if (!isset($this->lastRespuestasescalasCriteria) || !$this->lastRespuestasescalasCriteria->equals($criteria)) {
					$count = RespuestasescalasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collRespuestasescalass);
				}
			} else {
				$count = count($this->collRespuestasescalass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Respuestasescalas object to this object
	 * through the Respuestasescalas foreign key attribute.
	 *
	 * @param      Respuestasescalas $l Respuestasescalas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRespuestasescalas(Respuestasescalas $l)
	{
		if ($this->collRespuestasescalass === null) {
			$this->initRespuestasescalass();
		}
		if (!in_array($l, $this->collRespuestasescalass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRespuestasescalass, $l);
			$l->setEscalas($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Escalas is new, it will return
	 * an empty collection; or if this Escalas has previously
	 * been saved, it will retrieve related Respuestasescalass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Escalas.
	 */
	public function getRespuestasescalassJoinRespuestas($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRespuestasescalass === null) {
			if ($this->isNew()) {
				$this->collRespuestasescalass = array();
			} else {

				$criteria->add(RespuestasescalasPeer::ESCALAS_ID, $this->id);

				$this->collRespuestasescalass = RespuestasescalasPeer::doSelectJoinRespuestas($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RespuestasescalasPeer::ESCALAS_ID, $this->id);

			if (!isset($this->lastRespuestasescalasCriteria) || !$this->lastRespuestasescalasCriteria->equals($criteria)) {
				$this->collRespuestasescalass = RespuestasescalasPeer::doSelectJoinRespuestas($criteria, $con, $join_behavior);
			}
		}
		$this->lastRespuestasescalasCriteria = $criteria;

		return $this->collRespuestasescalass;
	}

	/**
	 * Clears out the collResultadosescalass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addResultadosescalass()
	 */
	public function clearResultadosescalass()
	{
		$this->collResultadosescalass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collResultadosescalass collection (array).
	 *
	 * By default this just sets the collResultadosescalass collection to an empty array (like clearcollResultadosescalass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initResultadosescalass()
	{
		$this->collResultadosescalass = array();
	}

	/**
	 * Gets an array of Resultadosescalas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Escalas has previously been saved, it will retrieve
	 * related Resultadosescalass from storage. If this Escalas is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Resultadosescalas[]
	 * @throws     PropelException
	 */
	public function getResultadosescalass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadosescalass === null) {
			if ($this->isNew()) {
			   $this->collResultadosescalass = array();
			} else {

				$criteria->add(ResultadosescalasPeer::ESCALAS_ID, $this->id);

				ResultadosescalasPeer::addSelectColumns($criteria);
				$this->collResultadosescalass = ResultadosescalasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ResultadosescalasPeer::ESCALAS_ID, $this->id);

				ResultadosescalasPeer::addSelectColumns($criteria);
				if (!isset($this->lastResultadosescalasCriteria) || !$this->lastResultadosescalasCriteria->equals($criteria)) {
					$this->collResultadosescalass = ResultadosescalasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastResultadosescalasCriteria = $criteria;
		return $this->collResultadosescalass;
	}

	/**
	 * Returns the number of related Resultadosescalas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Resultadosescalas objects.
	 * @throws     PropelException
	 */
	public function countResultadosescalass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collResultadosescalass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ResultadosescalasPeer::ESCALAS_ID, $this->id);

				$count = ResultadosescalasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ResultadosescalasPeer::ESCALAS_ID, $this->id);

				if (!isset($this->lastResultadosescalasCriteria) || !$this->lastResultadosescalasCriteria->equals($criteria)) {
					$count = ResultadosescalasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collResultadosescalass);
				}
			} else {
				$count = count($this->collResultadosescalass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Resultadosescalas object to this object
	 * through the Resultadosescalas foreign key attribute.
	 *
	 * @param      Resultadosescalas $l Resultadosescalas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addResultadosescalas(Resultadosescalas $l)
	{
		if ($this->collResultadosescalass === null) {
			$this->initResultadosescalass();
		}
		if (!in_array($l, $this->collResultadosescalass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collResultadosescalass, $l);
			$l->setEscalas($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Escalas is new, it will return
	 * an empty collection; or if this Escalas has previously
	 * been saved, it will retrieve related Resultadosescalass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Escalas.
	 */
	public function getResultadosescalassJoinResultados($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadosescalass === null) {
			if ($this->isNew()) {
				$this->collResultadosescalass = array();
			} else {

				$criteria->add(ResultadosescalasPeer::ESCALAS_ID, $this->id);

				$this->collResultadosescalass = ResultadosescalasPeer::doSelectJoinResultados($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ResultadosescalasPeer::ESCALAS_ID, $this->id);

			if (!isset($this->lastResultadosescalasCriteria) || !$this->lastResultadosescalasCriteria->equals($criteria)) {
				$this->collResultadosescalass = ResultadosescalasPeer::doSelectJoinResultados($criteria, $con, $join_behavior);
			}
		}
		$this->lastResultadosescalasCriteria = $criteria;

		return $this->collResultadosescalass;
	}

	/**
	 * Clears out the collValoresperados collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addValoresperados()
	 */
	public function clearValoresperados()
	{
		$this->collValoresperados = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collValoresperados collection (array).
	 *
	 * By default this just sets the collValoresperados collection to an empty array (like clearcollValoresperados());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initValoresperados()
	{
		$this->collValoresperados = array();
	}

	/**
	 * Gets an array of Valoresperado objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Escalas has previously been saved, it will retrieve
	 * related Valoresperados from storage. If this Escalas is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Valoresperado[]
	 * @throws     PropelException
	 */
	public function getValoresperados($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collValoresperados === null) {
			if ($this->isNew()) {
			   $this->collValoresperados = array();
			} else {

				$criteria->add(ValoresperadoPeer::ESCALAS_ID, $this->id);

				ValoresperadoPeer::addSelectColumns($criteria);
				$this->collValoresperados = ValoresperadoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ValoresperadoPeer::ESCALAS_ID, $this->id);

				ValoresperadoPeer::addSelectColumns($criteria);
				if (!isset($this->lastValoresperadoCriteria) || !$this->lastValoresperadoCriteria->equals($criteria)) {
					$this->collValoresperados = ValoresperadoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastValoresperadoCriteria = $criteria;
		return $this->collValoresperados;
	}

	/**
	 * Returns the number of related Valoresperado objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Valoresperado objects.
	 * @throws     PropelException
	 */
	public function countValoresperados(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collValoresperados === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ValoresperadoPeer::ESCALAS_ID, $this->id);

				$count = ValoresperadoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ValoresperadoPeer::ESCALAS_ID, $this->id);

				if (!isset($this->lastValoresperadoCriteria) || !$this->lastValoresperadoCriteria->equals($criteria)) {
					$count = ValoresperadoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collValoresperados);
				}
			} else {
				$count = count($this->collValoresperados);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Valoresperado object to this object
	 * through the Valoresperado foreign key attribute.
	 *
	 * @param      Valoresperado $l Valoresperado
	 * @return     void
	 * @throws     PropelException
	 */
	public function addValoresperado(Valoresperado $l)
	{
		if ($this->collValoresperados === null) {
			$this->initValoresperados();
		}
		if (!in_array($l, $this->collValoresperados, true)) { // only add it if the **same** object is not already associated
			array_push($this->collValoresperados, $l);
			$l->setEscalas($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Escalas is new, it will return
	 * an empty collection; or if this Escalas has previously
	 * been saved, it will retrieve related Valoresperados from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Escalas.
	 */
	public function getValoresperadosJoinPerfil($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EscalasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collValoresperados === null) {
			if ($this->isNew()) {
				$this->collValoresperados = array();
			} else {

				$criteria->add(ValoresperadoPeer::ESCALAS_ID, $this->id);

				$this->collValoresperados = ValoresperadoPeer::doSelectJoinPerfil($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ValoresperadoPeer::ESCALAS_ID, $this->id);

			if (!isset($this->lastValoresperadoCriteria) || !$this->lastValoresperadoCriteria->equals($criteria)) {
				$this->collValoresperados = ValoresperadoPeer::doSelectJoinPerfil($criteria, $con, $join_behavior);
			}
		}
		$this->lastValoresperadoCriteria = $criteria;

		return $this->collValoresperados;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPercentiless) {
				foreach ((array) $this->collPercentiless as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRespuestasescalass) {
				foreach ((array) $this->collRespuestasescalass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collResultadosescalass) {
				foreach ((array) $this->collResultadosescalass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collValoresperados) {
				foreach ((array) $this->collValoresperados as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPercentiless = null;
		$this->collRespuestasescalass = null;
		$this->collResultadosescalass = null;
		$this->collValoresperados = null;
			$this->aTests = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseEscalas:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseEscalas::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseEscalas
