<?php

/**
 * Base class that represents a row from the 'aspirantes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/14/11 19:33:58
 *
 * @package    lib.model.om
 */
abstract class BaseAspirantes extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AspirantesPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the apellido field.
	 * @var        string
	 */
	protected $apellido;

	/**
	 * The value for the cedula field.
	 * @var        string
	 */
	protected $cedula;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * @var        array Asistencias[] Collection to store aggregation of Asistencias objects.
	 */
	protected $collAsistenciass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAsistenciass.
	 */
	private $lastAsistenciasCriteria = null;

	/**
	 * @var        array Resultados[] Collection to store aggregation of Resultados objects.
	 */
	protected $collResultadoss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collResultadoss.
	 */
	private $lastResultadosCriteria = null;

	/**
	 * @var        array Resultadosparciales[] Collection to store aggregation of Resultadosparciales objects.
	 */
	protected $collResultadosparcialess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collResultadosparcialess.
	 */
	private $lastResultadosparcialesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AspirantesPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [apellido] column value.
	 * 
	 * @return     string
	 */
	public function getApellido()
	{
		return $this->apellido;
	}

	/**
	 * Get the [cedula] column value.
	 * 
	 * @return     string
	 */
	public function getCedula()
	{
		return $this->cedula;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Aspirantes The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AspirantesPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Aspirantes The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = AspirantesPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [apellido] column.
	 * 
	 * @param      string $v new value
	 * @return     Aspirantes The current object (for fluent API support)
	 */
	public function setApellido($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->apellido !== $v) {
			$this->apellido = $v;
			$this->modifiedColumns[] = AspirantesPeer::APELLIDO;
		}

		return $this;
	} // setApellido()

	/**
	 * Set the value of [cedula] column.
	 * 
	 * @param      string $v new value
	 * @return     Aspirantes The current object (for fluent API support)
	 */
	public function setCedula($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cedula !== $v) {
			$this->cedula = $v;
			$this->modifiedColumns[] = AspirantesPeer::CEDULA;
		}

		return $this;
	} // setCedula()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Aspirantes The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = AspirantesPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->apellido = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->cedula = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->password = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = AspirantesPeer::NUM_COLUMNS - AspirantesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Aspirantes object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AspirantesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AspirantesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collAsistenciass = null;
			$this->lastAsistenciasCriteria = null;

			$this->collResultadoss = null;
			$this->lastResultadosCriteria = null;

			$this->collResultadosparcialess = null;
			$this->lastResultadosparcialesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AspirantesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAspirantes:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AspirantesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAspirantes:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AspirantesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAspirantes:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAspirantes:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AspirantesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AspirantesPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AspirantesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AspirantesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAsistenciass !== null) {
				foreach ($this->collAsistenciass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collResultadoss !== null) {
				foreach ($this->collResultadoss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collResultadosparcialess !== null) {
				foreach ($this->collResultadosparcialess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = AspirantesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAsistenciass !== null) {
					foreach ($this->collAsistenciass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collResultadoss !== null) {
					foreach ($this->collResultadoss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collResultadosparcialess !== null) {
					foreach ($this->collResultadosparcialess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AspirantesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNombre();
				break;
			case 2:
				return $this->getApellido();
				break;
			case 3:
				return $this->getCedula();
				break;
			case 4:
				return $this->getPassword();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AspirantesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNombre(),
			$keys[2] => $this->getApellido(),
			$keys[3] => $this->getCedula(),
			$keys[4] => $this->getPassword(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AspirantesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNombre($value);
				break;
			case 2:
				$this->setApellido($value);
				break;
			case 3:
				$this->setCedula($value);
				break;
			case 4:
				$this->setPassword($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AspirantesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setApellido($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCedula($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPassword($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);

		if ($this->isColumnModified(AspirantesPeer::ID)) $criteria->add(AspirantesPeer::ID, $this->id);
		if ($this->isColumnModified(AspirantesPeer::NOMBRE)) $criteria->add(AspirantesPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(AspirantesPeer::APELLIDO)) $criteria->add(AspirantesPeer::APELLIDO, $this->apellido);
		if ($this->isColumnModified(AspirantesPeer::CEDULA)) $criteria->add(AspirantesPeer::CEDULA, $this->cedula);
		if ($this->isColumnModified(AspirantesPeer::PASSWORD)) $criteria->add(AspirantesPeer::PASSWORD, $this->password);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);

		$criteria->add(AspirantesPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Aspirantes (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNombre($this->nombre);

		$copyObj->setApellido($this->apellido);

		$copyObj->setCedula($this->cedula);

		$copyObj->setPassword($this->password);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAsistenciass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAsistencias($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getResultadoss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addResultados($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getResultadosparcialess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addResultadosparciales($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Aspirantes Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AspirantesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AspirantesPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collAsistenciass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAsistenciass()
	 */
	public function clearAsistenciass()
	{
		$this->collAsistenciass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAsistenciass collection (array).
	 *
	 * By default this just sets the collAsistenciass collection to an empty array (like clearcollAsistenciass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAsistenciass()
	{
		$this->collAsistenciass = array();
	}

	/**
	 * Gets an array of Asistencias objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Aspirantes has previously been saved, it will retrieve
	 * related Asistenciass from storage. If this Aspirantes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Asistencias[]
	 * @throws     PropelException
	 */
	public function getAsistenciass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsistenciass === null) {
			if ($this->isNew()) {
			   $this->collAsistenciass = array();
			} else {

				$criteria->add(AsistenciasPeer::ASPIRANTES_ID, $this->id);

				AsistenciasPeer::addSelectColumns($criteria);
				$this->collAsistenciass = AsistenciasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AsistenciasPeer::ASPIRANTES_ID, $this->id);

				AsistenciasPeer::addSelectColumns($criteria);
				if (!isset($this->lastAsistenciasCriteria) || !$this->lastAsistenciasCriteria->equals($criteria)) {
					$this->collAsistenciass = AsistenciasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAsistenciasCriteria = $criteria;
		return $this->collAsistenciass;
	}

	/**
	 * Returns the number of related Asistencias objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Asistencias objects.
	 * @throws     PropelException
	 */
	public function countAsistenciass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAsistenciass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AsistenciasPeer::ASPIRANTES_ID, $this->id);

				$count = AsistenciasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AsistenciasPeer::ASPIRANTES_ID, $this->id);

				if (!isset($this->lastAsistenciasCriteria) || !$this->lastAsistenciasCriteria->equals($criteria)) {
					$count = AsistenciasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAsistenciass);
				}
			} else {
				$count = count($this->collAsistenciass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Asistencias object to this object
	 * through the Asistencias foreign key attribute.
	 *
	 * @param      Asistencias $l Asistencias
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAsistencias(Asistencias $l)
	{
		if ($this->collAsistenciass === null) {
			$this->initAsistenciass();
		}
		if (!in_array($l, $this->collAsistenciass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAsistenciass, $l);
			$l->setAspirantes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aspirantes is new, it will return
	 * an empty collection; or if this Aspirantes has previously
	 * been saved, it will retrieve related Asistenciass from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aspirantes.
	 */
	public function getAsistenciassJoinEvaluaciones($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAsistenciass === null) {
			if ($this->isNew()) {
				$this->collAsistenciass = array();
			} else {

				$criteria->add(AsistenciasPeer::ASPIRANTES_ID, $this->id);

				$this->collAsistenciass = AsistenciasPeer::doSelectJoinEvaluaciones($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AsistenciasPeer::ASPIRANTES_ID, $this->id);

			if (!isset($this->lastAsistenciasCriteria) || !$this->lastAsistenciasCriteria->equals($criteria)) {
				$this->collAsistenciass = AsistenciasPeer::doSelectJoinEvaluaciones($criteria, $con, $join_behavior);
			}
		}
		$this->lastAsistenciasCriteria = $criteria;

		return $this->collAsistenciass;
	}

	/**
	 * Clears out the collResultadoss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addResultadoss()
	 */
	public function clearResultadoss()
	{
		$this->collResultadoss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collResultadoss collection (array).
	 *
	 * By default this just sets the collResultadoss collection to an empty array (like clearcollResultadoss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initResultadoss()
	{
		$this->collResultadoss = array();
	}

	/**
	 * Gets an array of Resultados objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Aspirantes has previously been saved, it will retrieve
	 * related Resultadoss from storage. If this Aspirantes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Resultados[]
	 * @throws     PropelException
	 */
	public function getResultadoss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadoss === null) {
			if ($this->isNew()) {
			   $this->collResultadoss = array();
			} else {

				$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

				ResultadosPeer::addSelectColumns($criteria);
				$this->collResultadoss = ResultadosPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

				ResultadosPeer::addSelectColumns($criteria);
				if (!isset($this->lastResultadosCriteria) || !$this->lastResultadosCriteria->equals($criteria)) {
					$this->collResultadoss = ResultadosPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastResultadosCriteria = $criteria;
		return $this->collResultadoss;
	}

	/**
	 * Returns the number of related Resultados objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Resultados objects.
	 * @throws     PropelException
	 */
	public function countResultadoss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collResultadoss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

				$count = ResultadosPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

				if (!isset($this->lastResultadosCriteria) || !$this->lastResultadosCriteria->equals($criteria)) {
					$count = ResultadosPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collResultadoss);
				}
			} else {
				$count = count($this->collResultadoss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Resultados object to this object
	 * through the Resultados foreign key attribute.
	 *
	 * @param      Resultados $l Resultados
	 * @return     void
	 * @throws     PropelException
	 */
	public function addResultados(Resultados $l)
	{
		if ($this->collResultadoss === null) {
			$this->initResultadoss();
		}
		if (!in_array($l, $this->collResultadoss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collResultadoss, $l);
			$l->setAspirantes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aspirantes is new, it will return
	 * an empty collection; or if this Aspirantes has previously
	 * been saved, it will retrieve related Resultadoss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aspirantes.
	 */
	public function getResultadossJoinPruebas($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadoss === null) {
			if ($this->isNew()) {
				$this->collResultadoss = array();
			} else {

				$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

				$this->collResultadoss = ResultadosPeer::doSelectJoinPruebas($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

			if (!isset($this->lastResultadosCriteria) || !$this->lastResultadosCriteria->equals($criteria)) {
				$this->collResultadoss = ResultadosPeer::doSelectJoinPruebas($criteria, $con, $join_behavior);
			}
		}
		$this->lastResultadosCriteria = $criteria;

		return $this->collResultadoss;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aspirantes is new, it will return
	 * an empty collection; or if this Aspirantes has previously
	 * been saved, it will retrieve related Resultadoss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aspirantes.
	 */
	public function getResultadossJoinEstadosresultados($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadoss === null) {
			if ($this->isNew()) {
				$this->collResultadoss = array();
			} else {

				$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

				$this->collResultadoss = ResultadosPeer::doSelectJoinEstadosresultados($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ResultadosPeer::ASPIRANTES_ID, $this->id);

			if (!isset($this->lastResultadosCriteria) || !$this->lastResultadosCriteria->equals($criteria)) {
				$this->collResultadoss = ResultadosPeer::doSelectJoinEstadosresultados($criteria, $con, $join_behavior);
			}
		}
		$this->lastResultadosCriteria = $criteria;

		return $this->collResultadoss;
	}

	/**
	 * Clears out the collResultadosparcialess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addResultadosparcialess()
	 */
	public function clearResultadosparcialess()
	{
		$this->collResultadosparcialess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collResultadosparcialess collection (array).
	 *
	 * By default this just sets the collResultadosparcialess collection to an empty array (like clearcollResultadosparcialess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initResultadosparcialess()
	{
		$this->collResultadosparcialess = array();
	}

	/**
	 * Gets an array of Resultadosparciales objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Aspirantes has previously been saved, it will retrieve
	 * related Resultadosparcialess from storage. If this Aspirantes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Resultadosparciales[]
	 * @throws     PropelException
	 */
	public function getResultadosparcialess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadosparcialess === null) {
			if ($this->isNew()) {
			   $this->collResultadosparcialess = array();
			} else {

				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				ResultadosparcialesPeer::addSelectColumns($criteria);
				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				ResultadosparcialesPeer::addSelectColumns($criteria);
				if (!isset($this->lastResultadosparcialesCriteria) || !$this->lastResultadosparcialesCriteria->equals($criteria)) {
					$this->collResultadosparcialess = ResultadosparcialesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastResultadosparcialesCriteria = $criteria;
		return $this->collResultadosparcialess;
	}

	/**
	 * Returns the number of related Resultadosparciales objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Resultadosparciales objects.
	 * @throws     PropelException
	 */
	public function countResultadosparcialess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collResultadosparcialess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				$count = ResultadosparcialesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				if (!isset($this->lastResultadosparcialesCriteria) || !$this->lastResultadosparcialesCriteria->equals($criteria)) {
					$count = ResultadosparcialesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collResultadosparcialess);
				}
			} else {
				$count = count($this->collResultadosparcialess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Resultadosparciales object to this object
	 * through the Resultadosparciales foreign key attribute.
	 *
	 * @param      Resultadosparciales $l Resultadosparciales
	 * @return     void
	 * @throws     PropelException
	 */
	public function addResultadosparciales(Resultadosparciales $l)
	{
		if ($this->collResultadosparcialess === null) {
			$this->initResultadosparcialess();
		}
		if (!in_array($l, $this->collResultadosparcialess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collResultadosparcialess, $l);
			$l->setAspirantes($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aspirantes is new, it will return
	 * an empty collection; or if this Aspirantes has previously
	 * been saved, it will retrieve related Resultadosparcialess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aspirantes.
	 */
	public function getResultadosparcialessJoinPruebas($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadosparcialess === null) {
			if ($this->isNew()) {
				$this->collResultadosparcialess = array();
			} else {

				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelectJoinPruebas($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

			if (!isset($this->lastResultadosparcialesCriteria) || !$this->lastResultadosparcialesCriteria->equals($criteria)) {
				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelectJoinPruebas($criteria, $con, $join_behavior);
			}
		}
		$this->lastResultadosparcialesCriteria = $criteria;

		return $this->collResultadosparcialess;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aspirantes is new, it will return
	 * an empty collection; or if this Aspirantes has previously
	 * been saved, it will retrieve related Resultadosparcialess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aspirantes.
	 */
	public function getResultadosparcialessJoinPreguntas($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadosparcialess === null) {
			if ($this->isNew()) {
				$this->collResultadosparcialess = array();
			} else {

				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelectJoinPreguntas($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

			if (!isset($this->lastResultadosparcialesCriteria) || !$this->lastResultadosparcialesCriteria->equals($criteria)) {
				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelectJoinPreguntas($criteria, $con, $join_behavior);
			}
		}
		$this->lastResultadosparcialesCriteria = $criteria;

		return $this->collResultadosparcialess;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Aspirantes is new, it will return
	 * an empty collection; or if this Aspirantes has previously
	 * been saved, it will retrieve related Resultadosparcialess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Aspirantes.
	 */
	public function getResultadosparcialessJoinOpciones($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AspirantesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collResultadosparcialess === null) {
			if ($this->isNew()) {
				$this->collResultadosparcialess = array();
			} else {

				$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelectJoinOpciones($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ResultadosparcialesPeer::ASPIRANTES_ID, $this->id);

			if (!isset($this->lastResultadosparcialesCriteria) || !$this->lastResultadosparcialesCriteria->equals($criteria)) {
				$this->collResultadosparcialess = ResultadosparcialesPeer::doSelectJoinOpciones($criteria, $con, $join_behavior);
			}
		}
		$this->lastResultadosparcialesCriteria = $criteria;

		return $this->collResultadosparcialess;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAsistenciass) {
				foreach ((array) $this->collAsistenciass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collResultadoss) {
				foreach ((array) $this->collResultadoss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collResultadosparcialess) {
				foreach ((array) $this->collResultadosparcialess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAsistenciass = null;
		$this->collResultadoss = null;
		$this->collResultadosparcialess = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAspirantes:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAspirantes::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAspirantes
