<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/19 00:00:50
sfConfig::add(array(
  'app_derechos_coneccion' => 'derechos',
  'app_derechos_plugin_success_signin_url' => 'principal/index',
  'app_derechos_plugin_modelo' => 'Administradores',
  'app_activo' => 1,
  'app_finalizado' => 3,
));
