<?php
/**
 * Skeleton subclass for representing a row from the 'asistencias' table.
 *
 * 
 *
 * This class was autogenerated by Propel sfContext::getInstance()-getUser()-getAttribute('usuarioId').4.2 on:
 *
 * 09/28/sfContext::getInstance()-getUser()-getAttribute('usuarioId')sfContext::getInstance()-getUser()-getAttribute('usuarioId') sfContext::getInstance()-getUser()-getAttribute('usuarioId')7:sfContext::getInstance()-getUser()-getAttribute('usuarioId')0:07
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Asistencias extends BaseAsistencias {

    public function postInsert(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Asistencias');
            $auditoria->setDescripcion('Aspirante : ' . $this->getAspirantes()->getCedula() . ' Evaluación : ' . $this->getEvaluaciones()->getNombre());
            $auditoria->setTipooperacion('Alta de asistencia');
            $auditoria->save();
        }
    }

    public function postUpdate(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli") {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Asistencias');
            $auditoria->setDescripcion('Aspirante : ' . $this->getAspirantes()->getCedula() . ' Evaluación : ' . $this->getEvaluaciones()->getNombre());
            $auditoria->setTipooperacion('Modificación de asistencia');
            $auditoria->save();
        }
    }

    public function postDelete(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli") {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Asistencias');
            $auditoria->setDescripcion('Aspirante : ' . $this->getAspirantes()->getCedula() . ' Evaluación : ' . $this->getEvaluaciones()->getNombre());
            $auditoria->setTipooperacion('Eliminación de asistencia');
            $auditoria->save();
        }
    }

}

// Asistencias
