<?php

/**
 * Skeleton subclass for representing a row from the 'aspirantes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/0:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Aspirantes extends BaseAspirantes {

    public function postInsert(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            if (sfContext::getInstance()->getUser()->getAttribute('usuarioId') != null) {
                $auditoria = new Auditorias();
                //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
                $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
                $auditoria->setObjeto('Aspirantes');
                $auditoria->setDescripcion(' Cedula : ' . $this->getCedula() . ' Nombre : ' . $this->getNombre() . ' Apellido : ' . $this->getApellido());
                $auditoria->setTipooperacion('Alta de aspirante');
                $auditoria->save();
            }
        }
    }

    public function postUpdate(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')            
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Aspirantes');
            $auditoria->setDescripcion(' Cedula : ' . $this->getCedula() . ' Nombre : ' . $this->getNombre() . ' Apellido : ' . $this->getApellido());
            $auditoria->setTipooperacion('Modificación de aspirante');
            $auditoria->save();
        }
    }

    public function postDelete(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Aspirantes');
            $auditoria->setDescripcion(' Cedula : ' . $this->getCedula() . ' Nombre : ' . $this->getNombre() . ' Apellido : ' . $this->getApellido());
            $auditoria->setTipooperacion('Eliminación de aspirante');
            $auditoria->save();
        }
    }

    public function getEdad() {
        $edad = $this->getFechanacimiento("Y/m/d");
        $anio_dif = 0;
        if($edad){
        list($anio, $mes, $dia) = explode("-", $edad);
        $anio_dif = date("Y") - $anio;
        $mes_dif = date("m") - $mes;
        $dia_dif = date("d") - $dia;
        if ($dia_dif < 0 || $mes_dif < 0)
            $anio_dif--;
        }
        return $anio_dif;
    }

}

// Aspirantes