<?php


/**
 * Skeleton subclass for representing a row from the 'auditorias' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/26/11 00:54:42
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Auditorias extends BaseAuditorias {

} // Auditorias
