<?php


/**
 * Skeleton subclass for performing query and update operations on the 'auditorias' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/26/11 00:54:42
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AuditoriasPeer extends BaseAuditoriasPeer 
{

  public static function getAuditorias($pagina,$rows,$fecha)
  {
    $criteria = new Criteria();        
    if($fecha!="--")
        $criteria->add(AuditoriasPeer::CREATED_AT,'%'.$fecha.'%',Criteria::LIKE);     
     $criteria->addDescendingOrderByColumn('auditorias.created_at');   
    $pager = new PropelPager($criteria, 'AuditoriasPeer', 'doSelectJoinAll', $page = $pagina, $rows);
    return $pager;
  }
} // AuditoriasPeer
