<?php


/**
 * Skeleton subclass for representing a row from the 'evaluaciones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/11 17:10:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Evaluaciones extends BaseEvaluaciones 
{
    public function postInsert(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(1);
             $auditoria->setObjeto('Evaluaciones');
             $auditoria->setDescripcion(' Nombre : '.$this->getNombre().' Perfil : '.$this->getPerfil()->getNombre().' Cantidad de aspirantes : '.$this->getCantidad());
             $auditoria->setTipooperacion('Alta de evaluación');
             $auditoria->save();             
     }
     
      public function postUpdate(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(1);
             $auditoria->setObjeto('Evaluaciones');
             $auditoria->setDescripcion(' Nombre : '.$this->getNombre().' Perfil : '.$this->getPerfil()->getNombre().' Cantidad de aspirantes : '.$this->getCantidad());
             $auditoria->setTipooperacion('Modificación de evaluación');
             $auditoria->save();   
     }
     
     public function preUpdate(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(1);
             $auditoria->setObjeto('Evaluaciones');
             $auditoria->setDescripcion(' Nombre : '.$this->getNombre().' Perfil : '.$this->getPerfil()->getNombre().' Cantidad de aspirantes : '.$this->getCantidad());
             $auditoria->setTipooperacion('Modificación de evaluación');
             $auditoria->save();   
     }

     public function preDelete(PropelPDO $con = null)
     {
             $auditoria = new Auditorias();
             //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
             $auditoria->setAdministradoresId(1);
             $auditoria->setObjeto('Evaluaciones');
             $auditoria->setDescripcion(' Nombre : '.$this->getNombre().' Perfil : '.$this->getPerfil()->getNombre().' Cantidad de aspirantes : '.$this->getCantidad());
             $auditoria->setTipooperacion('Eliminación de evaluación');
             $auditoria->save();          
     }

} // Evaluaciones
