<?php


/**
 * Skeleton subclass for performing query and update operations on the 'opciones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/29/11 23:43:34
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class OpcionesPeer extends BaseOpcionesPeer 
{
 public static function getOpcion($opcion,$tipoopcion)
  {
    $criteria = new Criteria();    

    $criteria->add(OpcionesPeer::TEXTO,$opcion,Criteria::EQUAL);     
    $criteria->add(OpcionesPeer::TIPOOPCION_ID,$tipoopcion,Criteria::EQUAL);   
    return (self::doSelectOne($criteria));
  }
  
   public static function getOpciones($pregunta)
  {
    $criteria = new Criteria();    
    $criteria->addJoin(self::TIPOOPCION_ID,TestsPeer::TIPOOPCION_ID,Criteria::INNER_JOIN); 
    $criteria->add(OpcionesPeer::TEXTO,$opcion,Criteria::EQUAL);
    return (self::doSelectJoinAll($criteria));
  }
} // OpcionesPeer
