<?php


/**
 * Skeleton subclass for performing query and update operations on the 'percentiles' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/11/11 16:15:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PercentilesPeer extends BasePercentilesPeer 
{
 public static function getPercentil($test,$puntaje)
  {
    $criteria = new Criteria();    
    $criteria->addJoin(PercentilesPeer::ESCALAS_ID,  EscalasPeer::ID,  Criteria::INNER_JOIN);
    $criteria->add(EscalasPeer::TESTS_ID,$test,Criteria::EQUAL);
    $criteria->add('percentiles.hasta',$puntaje,Criteria::GREATER_EQUAL);
    $criteria->addAnd('percentiles.desde',$puntaje,Criteria::LESS_EQUAL);    
    return (self::doSelectOne($criteria));
  }
} // PercentilesPeer
