<?php

/**
 * Skeleton subclass for representing a row from the 'pruebas' table.
 *
 * 
 *
 * This class was autogenerated by Propel sfContext::getInstance()-getUser()-getAttribute('usuarioId').4.2 on:
 *
 * 09/28/sfContext::getInstance()-getUser()-getAttribute('usuarioId')sfContext::getInstance()-getUser()-getAttribute('usuarioId') sfContext::getInstance()-getUser()-getAttribute('usuarioId')7:sfContext::getInstance()-getUser()-getAttribute('usuarioId')0:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Pruebas extends BasePruebas {

    public function postInsert(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            $auditoria = new Auditorias();

            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Pruebas');
            $auditoria->setDescripcion(' Test : ' . $this->getTests()->getTitulo() . ' Evaluación : ' . $this->getEvaluaciones()->getNombre());
            $auditoria->setTipooperacion('Alta de prueba');
            $auditoria->save();
        }
    }

    public function postUpdate(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Pruebas');
            $auditoria->setDescripcion(' Test : ' . $this->getTests()->getTitulo() . ' Evaluación : ' . $this->getEvaluaciones()->getNombre());
            $auditoria->setTipooperacion('Modificación de prueba');
            $auditoria->save();
        }
    }

    public function postDelete(PropelPDO $con = null) {
        if (sfConfig::get('sf_environment') != "cli" or sfContext::hasInstance()) {
            $auditoria = new Auditorias();
            //sfContext::getInstance()-getUser()-getAttribute('usuarioId')
            $auditoria->setAdministradoresId(sfContext::getInstance()->getUser()->getAttribute('usuarioId'));
            $auditoria->setObjeto('Pruebas');
            $auditoria->setDescripcion(' Test : ' . $this->getTests()->getTitulo() . ' Evaluación : ' . $this->getEvaluaciones()->getNombre());
            $auditoria->setTipooperacion('Eliminación de prueba');
            $auditoria->save();
        }
    }

}

// Pruebas
