<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tests' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/11 17:10:10
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TestsPeer extends BaseTestsPeer 
{
  public static function getTestHijos($padres)
  {      
    $criteria = new Criteria();          
   foreach($padres as $padre)
   {             
      $criteria->addOr(TestsPeer::TESTS_ID, $padre->getTests()->getId(), Criteria::IN);
   }
    $criteria->addAscendingOrderByColumn(self::TITULO);
    return (self::doSelectJoinAll($criteria));
  }
  
  public static function getTestsPadres()
  { 
      $criteria = new Criteria();       
      $criteria->add(self::TESTS_ID,null,Criteria::ISNULL);        
      return (self::doSelectJoinAll($criteria));
  }
  
  
} // TestsPeer
