<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/29 00:45:44
sfConfig::add(array(
  'app_derechos_coneccion' => 'derechos',
  'app_derechos_plugin_success_signin_url' => 'principal/evaluaciones',
  'app_derechos_plugin_modelo' => 'Aspirantes',
));
