<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/27 23:56:52

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=psicotest;host=ldpane.homelinux.org;port=3306',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
